// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Blueprint, _;

  _ = require('lodash');

  Blueprint = {
    make_type: {},
    export_attributes: [],
    cache: {},
    create: function() {
      var bp;
      bp = Object.create(this);
      bp.cache = {};
      return bp;
    },
    extend: function(body) {
      var bp;
      bp = this.create();
      _.assign(bp, body);
      return bp;
    },
    get: function(name) {
      var value;
      if (name in this.cache) {
        return this.cache[name];
      }
      value = this[name];
      if (_.isFunction(value)) {
        value = value.apply(this);
      }
      this.cache[name] = value;
      return value;
    },
    "export": function(overrides) {
      var i, len, name, ref, result;
      if (overrides === void 0) {
        overrides = {};
      }
      if (_.isFunction(this.make_type)) {
        result = this.make_type();
      } else {
        result = Object.create(this.make_type);
      }
      ref = this.export_attributes;
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        if (name in overrides) {
          result[name] = overrides[name];
        } else {
          result[name] = this.get(name);
        }
      }
      return result;
    },
    generate: function(overrides) {
      var bp;
      bp = this.create();
      return bp["export"](overrides);
    }
  };

  module.exports = Blueprint;

}).call(this);
